# CƠ BẢN VỀ PYTORCH

In [49]:
import torch

In [50]:
torch.cuda.is_available()

False

In [51]:
# sử dụng GPU và Cuda 

In [52]:
torch.cuda.current_device

<function torch.cuda.current_device() -> int>

In [53]:
#torch.cuda.get_device_name(0)

In [54]:
# Trả về mức sử dụng bộ nhớ gpu hiện tại theo tensors tính bằng byte cho thiết bị
torch.cuda.memory_allocated()

0

In [55]:
# Trả về bộ nhớ GPU hiện tại đc quản lý bởi bộ phân bổ bộ nhớ đệm theo byte
torch.cuda.memory_cached()

C:\Users\lhson\AppData\Local\Temp\ipykernel_49508\4180954611.py:2: FutureWarning: `torch.cuda.memory_cached` has been renamed to `torch.cuda.memory_reserved`
  torch.cuda.memory_cached()


0

Dataset with pytorch

In [56]:
# Loading data iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Iris.csv")
df.head()
# lấy ra bảng hoa iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [57]:
df.shape

(150, 6)

In [58]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(columns=['Species', 'Id'], axis= 1).values
y = le.fit_transform(df['Species'].values)

# chia dữ liệu thành tập train và test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)



In [59]:
print(f"Train size: {len(y_train)}")

Train size: 120


In [60]:
labels, counts = y_train.unique(return_counts=True)
print(f"Labels: {labels}\nCounts: {counts}")

Labels: tensor([0, 1, 2])
Counts: tensor([40, 41, 39])


In [61]:
# Tính đạo hàm bằng pytorch

# cho y = 2x^4 + x^3 + 3x^2 + 5x + 1

# tính y'

In [62]:
# Tạo một tensor với requires_grad=True 
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [63]:
# Định nghĩa hàm 
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [64]:
y.grad_fn

In [65]:
# Thực hiện việc truyền ngược và tính toán các gradient
y.backward()

# Kết quả đạo hàm
x.grad

tensor(93.)

In [66]:
# Bài tập
# Tính y' của y = 5x^6 + 3x^3 + 2x^1 + x + 2x + 5x^4 + 1

# Cho biết độ dốc của đa thức trên tại điểm nào

x = torch.tensor(2.0, requires_grad=True)
y = 5*x**6 + 3*x**3 + 2*x**1 + x + 2*x + 5*x**4 + 1
y.grad_fn
y.backward()
print("Độ dốc của đa thức tại điểm: ", x.grad)


Độ dốc của đa thức tại điểm:  tensor(1161.)


In [67]:
# BTVN 1:
# Tạo một tensor x có giá trị ban đầu là 2.0
# Định nghĩa hàm số và tính gradient
# y = x^3 + 2x^2 + 5x + 1
# Hãy tính dy/dx tại giá trị của x
# Dùng phương pháp gradient descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp

# BTVN 2:
# Tạo một tập dữ liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10) và y là số điểm được tính theo công thức y = 3x + 5+ noise
# với noise là một giá trị ngẫu nhiên nhỏ
# 1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad=True
# 2. Tính MSE
# 3. Tính gradient
# 4. Cập nhật tham số w và b bằng gradient descent với learning rate alpha = 0.01
# 5. Lặp lại quá trình 2-4 trong 1000 vòng lặp và quan sát sự hội tụ của mô hình


In [68]:
# BTVN 1:
x = torch.tensor(2.0, requires_grad=True)

In [69]:
# Learning rate
alpha = 0.1

In [70]:
# Số vòng lặp
num_iterations = 10

In [71]:
# Lặp lại quá trình cập nhật theo Gradient Descent
for i in range(num_iterations):
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()  # Tính gradient của y theo x
    with torch.no_grad():  
        x -= alpha * x.grad 
        x.grad.zero_()  
    print(f"Vòng lặp {i+1}: x = {x.item()}")


Vòng lặp 1: x = -0.5
Vòng lặp 2: x = -0.875
Vòng lặp 3: x = -1.2546875476837158
Vòng lặp 4: x = -1.7250847816467285
Vòng lặp 5: x = -2.427826166152954
Vòng lặp 6: x = -3.7249975204467773
Vòng lặp 7: x = -6.897680282592773
Vòng lặp 8: x = -18.912006378173828
Vòng lặp 9: x = -119.14640808105469
Vòng lặp 10: x = -4330.74755859375


In [72]:
# Kết quả cuối cùng sau 10 vòng lặp
print(f"Giá trị tối ưu của x sau {num_iterations} vòng lặp: {x.item()}")

Giá trị tối ưu của x sau 10 vòng lặp: -4330.74755859375


In [73]:
# BTVN 2:
# Tạo dữ liệu giả lập
torch.manual_seed(42)  # Để kết quả tái lặp
x = torch.randint(1, 11, (50, 1), dtype=torch.float32)  # 50 điểm dữ liệu, giá trị từ 1 đến 10
noise = torch.randn(50, 1) * 2  # Nhiễu nhỏ
y = 3 * x + 5 + noise  # Công thức y = 3x + 5 + noise

In [74]:
#Khởi tạo tham số w, b ngẫu nhiên
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [75]:
#Huấn luyện mô hình với Gradient Descent
learning_rate = 0.01 # Tốc độ học
epochs = 1000  # Số vòng lặp

In [76]:
# Lặp qua số lượng epoch cho trước
for epoch in range(epochs):
    # Dự đoán giá trị y
    y_pred = w * x + b
    
    # Tính MSE loss
    loss = torch.mean((y_pred - y) ** 2)

    # Tính gradient
    loss.backward()

    # Cập nhật tham số
    with torch.no_grad():  # Tắt gradient tracking
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    # Xóa gradient sau mỗi vòng lặp
    w.grad.zero_()
    b.grad.zero_()

    # In loss sau mỗi 100 epoch
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}, w: {w.item():.4f}, b: {b.item():.4f}")


Epoch 0, Loss: 753.3033, w: 2.8159, b: -0.0599
Epoch 100, Loss: 6.1925, w: 3.4777, b: 1.8417
Epoch 200, Loss: 4.7286, w: 3.3064, b: 3.0278
Epoch 300, Loss: 4.0705, w: 3.1915, b: 3.8230
Epoch 400, Loss: 3.7747, w: 3.1144, b: 4.3562
Epoch 500, Loss: 3.6418, w: 3.0628, b: 4.7136
Epoch 600, Loss: 3.5820, w: 3.0281, b: 4.9533
Epoch 700, Loss: 3.5551, w: 3.0049, b: 5.1139
Epoch 800, Loss: 3.5430, w: 2.9894, b: 5.2217
Epoch 900, Loss: 3.5376, w: 2.9789, b: 5.2939


In [77]:
print(f"Final parameters - w: {w.item():.4f}, b: {b.item():.4f}")

Final parameters - w: 2.9720, b: 5.3419


In [78]:
# Pytorch with tensor
import torch
import numpy as np

In [79]:
torch.__version__

'2.5.1+cpu'

In [80]:
# Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1, 2, 3, 4, 5])# Mảng numpy
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [81]:
x = torch.from_numpy(arr) # Chuyển mảng numpy sang tensor
print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [82]:
print(x.dtype)
print(type(x))

torch.int32
<class 'torch.Tensor'>


In [83]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [84]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [85]:
arr = np.arange(0, 5)
x = torch.from_numpy(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [86]:
arr[0] = 99
print(x)

tensor([99,  1,  2,  3,  4], dtype=torch.int32)


In [87]:
arr = np.arange(0, 5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [88]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [89]:
# BTVN 3: Giải thích lý do tại sao cho 2 trường hợp trên

torch.from_numpy(arr)

Tạo một tensor chia sẻ bộ nhớ với mảng NumPy gốc (arr)
Nếu thay đổi arr, giá trị trong tensor x cũng thay đổi

torch.tensor(arr)

Tạo một tensor mới độc lập với arr
Nếu thay đổi arr, giá trị trong tensor x không bị ảnh hưởng

In [90]:
# BTVN 4: bạn hãy giúp thầy về nhà tạo tensor với:
# Empyty
# Zeros
# Ones
# Random
# Reshape với view và view as


# Deadline: 23h59 ngày 16/03/2025

In [91]:
# Tạo tensor với empty
empty_tensor = torch.empty(2, 3)
print(empty_tensor)

tensor([[-1.6287e+37,  1.0734e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [92]:
# Tensor với zeros
zeros_tensor = torch.zeros(2, 3)
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [93]:
# Tensor với ones
ones_tensor = torch.ones(2, 3)
print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [94]:
# Tensor với random
random_tensor = torch.rand(2, 3)
print(random_tensor)

tensor([[0.5014, 0.3139, 0.4654],
        [0.1612, 0.1568, 0.2083]])


In [95]:
# Reshape tensor với view
reshape_tensor_view = random_tensor.view(3, 2)
print(reshape_tensor_view)

tensor([[0.5014, 0.3139],
        [0.4654, 0.1612],
        [0.1568, 0.2083]])


In [96]:
# Reshape tensor với view_as
reshape_tensor_view_as = random_tensor.view_as(ones_tensor)
print(reshape_tensor_view_as)

tensor([[0.5014, 0.3139, 0.4654],
        [0.1612, 0.1568, 0.2083]])
